apiVersion: v1
kind: Service
metadata:
  app: hello-python
  k8s-app: hello-python
  name: hello-python
spec:
  selector:
    app: hello-python
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: public.ecr.aws/s7j9a1w6/docker-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
