apiVersion: v1
kind: Service
metadata:
  name: new-python
spec:
  selector:
    app: new-python
  ports:
  - name: http
    protocol: TCP
    port: 6001
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-python
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-python
  template:
    metadata:
      labels:
        app: new-python
    spec:
      containers:
      - name: new-python
        image: phanick/new-python:22
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
