
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python 
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        ports:
        - containerPort: 5500
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: hello-py-service
spec:
  selector:
    app: hello-python 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5600
    targetPort: 5500
    
