apiVersion: v1
kind: Service
metadata:
  name: a2-python
spec:
  selector:
    app: a2-python
  ports:
  - name: http
    protocol: TCP
    port: 6001
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2-python
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a2-python
  template:
    metadata:
      labels:
        app: a2-python
    spec:
      containers:
      - name: a2-python
        image: phanick/a2-python:2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
