apiVersion: v1
kind: Service
metadata:
  name: a10-python
spec:
  selector:
    app: a10-python
  ports:
  - name: http
    protocol: TCP
    port: 6002
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a10-python
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a10-python
  template:
    metadata:
      labels:
        app: a10-python
    spec:
      containers:
      - name: a10-python
        image: phanick/a10-python:10
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
