apiVersion: v1
kind: Service
metadata:
  app: my-python
  k8s-app: my-python
  name: my-python
spec:
  selector:
    app: my-python
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python
  template:
    metadata:
      labels:
        app: my-python
    spec:
      containers:
      - name: my-python
        image: phanick/my-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
